version: "0.5"

processes:
  install:
    command: bun install
    availability:
      restart: no

  build-ext:
    command: bun --cwd apps/controller-ext build
    availability:
      restart: no
    depends_on:
      install:
        condition: process_completed_successfully

  server:
    command: bun --cwd apps/server start
    depends_on:
      build-ext:
        condition: process_completed_successfully

  agent:
    command: bun --cwd apps/agent dev
    depends_on:
      build-ext:
        condition: process_completed_successfully
