/**
 * @license
 * Copyright 2025 BrowserOS
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

export interface OAuthMcpServer {
  name: string // Exact name to pass to Klavis API
  description: string
}

/**
 * Curated list of popular OAuth MCP servers supported via Klavis
 */
export const OAUTH_MCP_SERVERS: OAuthMcpServer[] = [
  { name: 'Gmail', description: 'Send, read, and search emails' },
  { name: 'Google Calendar', description: 'Create events, manage calendars' },
  { name: 'Google Docs', description: 'Create and edit documents' },
  { name: 'Google Drive', description: 'Upload, download, and manage files' },
  { name: 'Google Sheets', description: 'Create and edit spreadsheets' },
  { name: 'Slack', description: 'Post messages, manage channels' },
  { name: 'LinkedIn', description: 'Post updates, manage connections' },
  { name: 'Notion', description: 'Create pages, manage databases' },
  { name: 'Airtable', description: 'Manage bases, tables, and records' },
  { name: 'Confluence', description: 'Create and manage documentation' },
  { name: 'GitHub', description: 'Manage repos, issues, pull requests' },
  { name: 'GitLab', description: 'Manage repos, issues, merge requests' },
  { name: 'Linear', description: 'Create issues, manage cycles' },
  { name: 'Jira', description: 'Create issues, manage sprints' },
  { name: 'Figma', description: 'Access and manage design files' },
  { name: 'Canva', description: 'Create and manage designs' },
  { name: 'Salesforce', description: 'Manage leads, contacts, opportunities' },
  { name: 'ClickUp', description: 'Manage tasks, projects, and workflows' },
  { name: 'Asana', description: 'Organize and track team projects' },
  { name: 'Monday', description: 'Manage work and team collaboration' },
  { name: 'Microsoft Teams', description: 'Chat, meet, and collaborate' },
  { name: 'Outlook Mail', description: 'Send, read, and manage emails' },
  { name: 'Outlook Calendar', description: 'Schedule meetings and events' },
  { name: 'Supabase', description: 'Manage databases and backend services' },
  { name: 'Vercel', description: 'Deploy and manage web applications' },
  { name: 'Postman', description: 'Test and manage APIs' },
  { name: 'Stripe', description: 'Manage payments and subscriptions' },
  { name: 'Cloudflare', description: 'Manage domains, DNS, and security' },
  { name: 'Brave Search', description: 'Search the web privately' },
  { name: 'Mem0', description: 'Store and retrieve AI memory' },
  { name: 'Exa', description: 'AI-powered semantic web search' },
  { name: 'Dropbox', description: 'Store and share files in the cloud' },
  { name: 'OneDrive', description: 'Store and sync files with Microsoft' },
  { name: 'WordPress', description: 'Manage websites and blog content' },
  { name: 'YouTube', description: 'Access video info and transcripts' },
  { name: 'Box', description: 'Manage and share enterprise files' },
  { name: 'HubSpot', description: 'Manage contacts, deals, and marketing' },
  { name: 'PostHog', description: 'Query analytics, manage feature flags' },
  { name: 'Mixpanel', description: 'Analyze user behavior and metrics' },
  { name: 'Discord', description: 'Send messages and manage servers' },
  { name: 'WhatsApp', description: 'Send messages and manage conversations' },
  { name: 'Shopify', description: 'Manage products, orders, and store' },
  { name: 'Cal.com', description: 'Schedule meetings and manage availability' },
  { name: 'Resend', description: 'Send transactional and marketing emails' },
  { name: 'Google Forms', description: 'Create and manage forms and surveys' },
  { name: 'Zendesk', description: 'Manage support tickets and customers' },
  { name: 'Intercom', description: 'Manage customer messaging and support' },
  {
    name: 'Google Cloud',
    description: 'Manage cloud infrastructure and services',
  },
  { name: 'Google Jobs', description: 'Manage job postings and applications' },
  { name: 'Hacker News', description: 'Browse tech news and discussions' },
  { name: 'Instagram', description: 'Manage content and analyze engagement' },
  {
    name: 'Calendly',
    description: 'Automate scheduling and calendar management',
  },
  { name: 'Attio', description: 'Manage CRM and customer relationships' },
  { name: 'Gong', description: 'Analyze sales conversations and calls' },
  { name: 'Mailchimp', description: 'Manage email marketing and audiences' },
  { name: 'Sentry', description: 'Monitor errors and track performance' },
  { name: 'Netlify', description: 'Deploy and manage web applications' },
  { name: 'Pipedrive', description: 'Manage sales pipeline and leads' },
  { name: 'Amplitude', description: 'Analyze product usage and user behavior' },
  { name: 'Motion', description: 'Manage tasks and automate scheduling' },
  { name: 'Coinbase', description: 'Access crypto data and manage portfolios' },
  { name: 'Freshdesk', description: 'Manage customer support tickets' },
  { name: 'Help Scout', description: 'Manage customer support conversations' },
  { name: 'HeyGen', description: 'Generate AI-powered videos and avatars' },
  { name: 'Honeycomb', description: 'Monitor observability and tracing' },
  { name: 'HuggingFace', description: 'Access ML models and inference' },
  { name: 'Jotform', description: 'Create and manage forms and submissions' },
  { name: 'Klaviyo', description: 'Manage marketing campaigns and data' },
  { name: 'LiveAgent', description: 'Manage support tickets and live chat' },
  { name: 'Metabase', description: 'Query data and manage analytics' },
  { name: 'Moneybird', description: 'Manage accounting and finances' },
  { name: 'OpenRouter', description: 'Access and compare AI models' },
  { name: 'Pagerduty', description: 'Manage incidents and on-call alerts' },
  { name: 'PayPal', description: 'Process payments and transactions' },
  { name: 'Perplexity', description: 'AI-powered search and research' },
  { name: 'PostgreSQL', description: 'Query and manage databases' },
  { name: 'Sendgrid', description: 'Send and manage email campaigns' },
  { name: 'ServiceNow', description: 'Manage IT service workflows' },
  { name: 'Snowflake', description: 'Query and analyze large-scale data' },
  { name: 'Square', description: 'Manage payments, sales, and inventory' },
  { name: 'Tavily', description: 'AI-optimized web search and retrieval' },
  { name: 'Affinity', description: 'Manage CRM contacts and relationships' },
  { name: 'Close', description: 'Manage sales pipeline and leads' },
  { name: 'Clockwise', description: 'Optimize calendars and scheduling' },
  { name: 'Dialpad', description: 'Manage business communications' },
  {
    name: 'Docusign',
    description: 'Manage electronic signatures and agreements',
  },
  { name: 'ElevenLabs', description: 'Generate AI voice and audio' },
  { name: 'Fathom', description: 'AI-powered meeting notes and summaries' },
  { name: 'Fireflies', description: 'Transcribe and analyze meetings' },
  { name: 'Gorgias', description: 'Manage e-commerce customer support' },
  { name: 'Zoho Desk', description: 'Manage support tickets and helpdesk' },
  { name: 'Zoho Mail', description: 'Manage email and communications' },
  { name: 'Plai', description: 'Manage social media advertising' },
  {
    name: 'Weights and Biases',
    description: 'Track ML experiments and training',
  },
  { name: 'Sharesight', description: 'Track portfolios and investments' },
]
